# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 08ed0c891c78cc54f4b5810fef033cc72fc28402d617fb262996f7146922b1f0aa2bfcab0cce0de25608d6b9323b4f0f77d4a6aa76fe9957b281d1c97af1afe0

test:
  secret_key_base: eb793096a0badeb0f7b2f1555cc80c72105dcc45bc8794d70a85e08de6b2ff80dc2c7b8d33941a9e0fd596e4e69f228e31c818c2e0d2a9b1bcbd14377fcfcdfd

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
